### ISSUE TITLE
How do I install without using pip?

### ISSUE THREAD

**Issue by jeffyjeffy1023** [ShadowFire5650/legomario#1]
Since this isn't on pip yet, how do I install it? I wanna try this out with my Mario, and probably Luigi too.

**Comment by ModestBitboard** [comment]
in order to use it all you need to do is put the "legomario" folder in the same directory as your script...

**Comment by jeffyjeffy1023** [comment]
Well, the thing is that every time I try to run any of the examples I just get this:
Traceback (most recent call last):
  File "example1.py", line 2, in <module>
    from legomario import Mario
ModuleNotFoundError: No module named 'legomario'
(I'm using python 3.7.9 btw if that helps at all)

**Comment by ModestBitboard** [comment]
Move the examples into the same folder as README.md (the legomario-main folder), that will solve the problem...

**Comment by jeffyjeffy1023** [comment]
Ah. Alright, my bad! Thank you!

**Comment by ModestBitboard** [comment]
# You're Welcome!
Have fun playing around with lego Mario! Would it be alright if I close this issue now?

**Comment by jeffyjeffy1023** [comment]
Sure, go ahead! I'll let you know if I ever need more help.
